
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Santillanes
 */


    
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form manu
     */
    
    class RoundedBorder implements Border {

    private int radius;

    RoundedBorder(int radius) {
        this.radius = radius;
    }

    public Insets getBorderInsets(Component c) {
        return new Insets(this.radius + 1, this.radius + 1, this.radius + 2, this.radius);
    }

    public boolean isBorderOpaque() {
        return true;
    }

    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        g.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
    }
}
    
    public menu() {
        initComponents();
        
        setSize(1280, 720);
        this.setLocationRelativeTo(null);
        
        btnEscanear.setBorder(new RoundedBorder(30));
        btnSalir.setBorder(new RoundedBorder(30));
        btnVisita.setBorder(new RoundedBorder(30));
        btnServicios.setBorder(new RoundedBorder(30));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnVisita = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnServicios = new javax.swing.JButton();
        btnEscanear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("de Servicios");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(927, 450, 130, 30);

        btnVisita.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        btnVisita.setForeground(new java.awt.Color(255, 255, 255));
        btnVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registro.png"))); // NOI18N
        btnVisita.setText("Registro Visitantes");
        btnVisita.setContentAreaFilled(false);
        btnVisita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVisita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisita);
        btnVisita.setBounds(516, 247, 249, 249);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("sin QR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 450, 202, 30);

        btnServicios.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registro.png"))); // NOI18N
        btnServicios.setText("Registro");
        btnServicios.setContentAreaFilled(false);
        btnServicios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnServicios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(btnServicios);
        btnServicios.setBounds(865, 247, 249, 249);

        btnEscanear.setBackground(new java.awt.Color(255, 255, 255));
        btnEscanear.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        btnEscanear.setForeground(new java.awt.Color(255, 255, 255));
        btnEscanear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qr2.0.png"))); // NOI18N
        btnEscanear.setText("Escanear QR o");
        btnEscanear.setContentAreaFilled(false);
        btnEscanear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEscanear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEscanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscanearActionPerformed(evt);
            }
        });
        getContentPane().add(btnEscanear);
        btnEscanear.setBounds(167, 247, 249, 249);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teclear Código");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(211, 450, 162, 30);

        btnSalir.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(546, 583, 160, 46);

        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo 1280x720 2.0.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        inicio nF = new inicio();
        nF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEscanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscanearActionPerformed
        // TODO add your handling code here:
        opcion1 nF = new opcion1();
        nF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEscanearActionPerformed

    private void btnVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitaActionPerformed
        // TODO add your handling code here:
        opcion2 nF = new opcion2();
        nF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVisitaActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        // TODO add your handling code here:
        opcion3 nF = new opcion3();
        nF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscanear;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnVisita;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
